apiVersion: v1
kind: Service
metadata:
  name: {{ template "caluma.fullname" . }}-backend
  labels:
{{ include "caluma.labels" . | indent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "caluma.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
